# coding: utf-8

"""
    Gitea API

    This documentation describes the Gitea API.  # noqa: E501

    OpenAPI spec version: {{AppVer | JSEscape}}
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import gitea_client
from gitea_client.models.notification_subject import NotificationSubject  # noqa: E501
from gitea_client.rest import ApiException


class TestNotificationSubject(unittest.TestCase):
    """NotificationSubject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNotificationSubject(self):
        """Test NotificationSubject"""
        # FIXME: construct object with mandatory attributes with example values
        # model = gitea_client.models.notification_subject.NotificationSubject()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
