# coding: utf-8

"""
    Gitea API

    This documentation describes the Gitea API.  # noqa: E501

    OpenAPI spec version: {{AppVer | JSEscape}}
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import gitea_client
from gitea_client.models.label_template import LabelTemplate  # noqa: E501
from gitea_client.rest import ApiException


class TestLabelTemplate(unittest.TestCase):
    """LabelTemplate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLabelTemplate(self):
        """Test LabelTemplate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = gitea_client.models.label_template.LabelTemplate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
