# coding: utf-8

"""
    Gitea API

    This documentation describes the Gitea API.  # noqa: E501

    OpenAPI spec version: {{AppVer | JSEscape}}
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import gitea_client
from gitea_client.models.issue_config_contact_link import IssueConfigContactLink  # noqa: E501
from gitea_client.rest import ApiException


class TestIssueConfigContactLink(unittest.TestCase):
    """IssueConfigContactLink unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIssueConfigContactLink(self):
        """Test IssueConfigContactLink"""
        # FIXME: construct object with mandatory attributes with example values
        # model = gitea_client.models.issue_config_contact_link.IssueConfigContactLink()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
