# coding: utf-8

"""
    Gitea API

    This documentation describes the Gitea API.  # noqa: E501

    OpenAPI spec version: {{AppVer | JSEscape}}
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import gitea_client
from gitea_client.models.git_tree_response import GitTreeResponse  # noqa: E501
from gitea_client.rest import ApiException


class TestGitTreeResponse(unittest.TestCase):
    """GitTreeResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGitTreeResponse(self):
        """Test GitTreeResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = gitea_client.models.git_tree_response.GitTreeResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
